### ISSUE TITLE
rfam failing for small sample files

### ISSUE THREAD

**Issue by mflynn-lanl** [microbiomedata/metaT#35] opened 2024-06-28 15:58 UTC
the task `rfam.run` is failing for small sample files. This is because the <project_id>_rfam.tbl is empty and so the grep command returns no results. Since we have `set -euo pipefail` this results in the task failing.

**Comment by mhuntemann** [comment] 2024-06-28 19:20
Hi,
Maybe you guys are not running the latest version of the script from the original pipeline.
It has a check for that that got added in May last year.
You can find the latest version here:
https://code.jgi.doe.gov/img/img-pipelines/img-annotation-pipeline/-/blob/main/bin/structural_annotation/cmsearch_rfams.sh?ref_type=heads

**Comment by mflynn-lanl** [comment] 2024-07-09 22:37
@mhuntemann, where do we use that script? I don't see it used in `rfam.wdl`

**Comment by ssarrafan** [comment] 2024-07-12 19:44
@mflynn-lanl @vlilanl looks like you're waiting to hear back on more information. I'll move this to the new sprint.
FYI @aclum

**Comment by aclum** [comment] 2024-07-12 21:23
@mflynn-lanl The problem is that metatranscriptome annotation, what is in this repo, is out of sync. the annotation repo does have this workaround, see https://github.com/microbiomedata/mg_annotation/blob/master/rfam.wdl. 
Closing this as won't fix as @kaijli  is working on getting everything synchronized with the latest code.

cc @vlilanl

**Closed by aclum** 2024-07-12 21:23 UTC
